# Copyright 2013 Jike Inc. All Rights Reserved.
# Author: Liqiang Guo(guoliqiang@jike.com)
# Date  : 2013-09-09 15:26:45


WORK_ROOT=../../..
PROJ_NAME=third_part/geohash/internal


all:
	$(WORK_ROOT)/develop/snake/snake.sh t=*
	#cp $(WORK_ROOT)/.snake/dbg/$(PROJ_NAME)/email $(WORK_ROOT)/$(PROJ_NAME)/; \

opt:


clean:
