# Copyright 2015. All Rights Reserved.
# Author: Liqiang Guo(guoliqiang2006@gmail.com)
# Date  : 2015-09-13 03:12:40


WORK_ROOT=../../..
PROJ_NAME=nltk/lbfgs/internal


all:
	$(WORK_ROOT)/develop/snake/snake.sh t=*
	if test $$? -ne 0; then exit 1; fi; \

#  cp $(WORK_ROOT)/.snake/dbg/$(PROJ_NAME)/sample $(WORK_ROOT)/$(PROJ_NAME)/; \

opt:


clean:
	rm -rf sample
