# Copyright 2013 Jike Inc. All Rights Reserved.
# Author: Liqiang Guo(guoliqiang@jike.com)
# Date  : 2013-09-13 11:27:59


WORK_ROOT=../../..
PROJ_NAME=util/xml_parser/internal


all:
	$(WORK_ROOT)/develop/snake/snake.sh t=*


opt:


clean:

