# Copyright 2013. All Rights Reserved.
# Author: Liqiang Guo(guoliqiang2006@gmail.com)
# Date  : 2013-09-08 03:12:40


WORK_ROOT=../../..
PROJ_NAME=nltk/svm/internal


all:
	$(WORK_ROOT)/develop/snake/snake.sh t=*


opt:


clean:

