# Copyright 2013 Jike Inc. All Rights Reserved.
# Author: Liqiang Guo(guoliqiang@jike.com)
# Date  : 2013-09-08 03:12:40


WORK_ROOT=../../..
PROJ_NAME=nltk/svr/internal


all:
	$(WORK_ROOT)/develop/snake/snake.sh t=*


opt:


clean:

