/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef clustering_CONSTANTS_H
#define clustering_CONSTANTS_H

#include "clustering_types.h"



class clusteringConstants {
 public:
  clusteringConstants();

};

extern const clusteringConstants g_clustering_constants;



#endif
