WORK_ROOT=../../..
PROJ_NAME=third_part/indri5.6/build_index
all:
	$(WORK_ROOT)/develop/snake/snake.sh t=*
	cp $(WORK_ROOT)/.snake/dbg/$(PROJ_NAME)/build_index $(WORK_ROOT)/$(PROJ_NAME)/; \

opt:
	$(WORK_ROOT)/develop/snake/snake.sh t=* c=opt

clean:

