# Copyright 2015. All Rights Reserved.
# Author: Liqiang Guo(guoliqiang2006@gmail.com)
# Date  : 2015-09-13 03:12:40


WORK_ROOT=../../..
PROJ_NAME=nltk/lda/internal


all:
	$(WORK_ROOT)/develop/snake/snake.sh t=*


opt:


clean:

