# CMake generated Testfile for 
# Source directory: /home/guoliqiang/git-coding/coding/third_part/mysql/mysql-5.5.24
# Build directory: /home/guoliqiang/git-coding/coding/third_part/mysql/mysql-5.5.24
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
SUBDIRS(cmd-line-utils/libedit)
SUBDIRS(storage/federated)
SUBDIRS(storage/myisammrg)
SUBDIRS(storage/example)
SUBDIRS(storage/csv)
SUBDIRS(storage/myisam)
SUBDIRS(storage/heap)
SUBDIRS(storage/innobase)
SUBDIRS(storage/archive)
SUBDIRS(storage/perfschema)
SUBDIRS(storage/blackhole)
SUBDIRS(plugin/auth)
SUBDIRS(plugin/audit_null)
SUBDIRS(plugin/daemon_example)
SUBDIRS(plugin/fulltext)
SUBDIRS(plugin/semisync)
SUBDIRS(include)
SUBDIRS(dbug)
SUBDIRS(strings)
SUBDIRS(vio)
SUBDIRS(regex)
SUBDIRS(mysys)
SUBDIRS(libmysql)
SUBDIRS(unittest/mytap)
SUBDIRS(unittest/mysys)
SUBDIRS(extra)
SUBDIRS(tests)
SUBDIRS(client)
SUBDIRS(sql)
SUBDIRS(sql/share)
SUBDIRS(libservices)
SUBDIRS(mysql-test)
SUBDIRS(mysql-test/lib/My/SafeProcess)
SUBDIRS(support-files)
SUBDIRS(scripts)
SUBDIRS(sql-bench)
SUBDIRS(man)
SUBDIRS(packaging/WiX)
