# Copyright 2013 Jike Inc. All Rights Reserved.
# Author: Liqiang Guo(guoliqiang@jike.com)
# Date  : 2013-07-11 11:26:50


WORK_ROOT=../../..
PROJ_NAME=third_part/zk_manager/unittest


all:
	$(WORK_ROOT)/develop/snake/snake.sh t=*
	cp $(WORK_ROOT)/.snake/dbg/$(PROJ_NAME)/zk_manager_unittest $(WORK_ROOT)/$(PROJ_NAME)/; \


opt:
	$(WORK_ROOT)/develop/snake/snake.sh t=* c=opt
	cp $(WORK_ROOT)/.snake/opt/$(PROJ_NAME)/zk_manager_unittet $(WORK_ROOT)/$(PROJ_NAME)/; \


clean:

