
// Generated by /home/guoliqiang/qfs/src/cc/common/buildversgit.sh. Do not edit.

#include "third_part/qfs/common/Version.h"
#include "third_part/qfs/common/hsieh_hash.h"

namespace KFS {

const std::string KFS_BUILD_INFO_STRING=
"KFS_BUILD_INFO_START\n"
"host: ubuntu\n"
"user: root\n"
"date: Thu Oct 22 19:53:13 PDT 2015\n"
"build type: RelWithDebInfo\n"
"boost: /usr/include /usr/lib/libboost_regex-mt.so\n"
"source dir: /home/guoliqiang/qfs\n"
"release: 1.1.4\n"
"git config:\n"
"core.repositoryformatversion=0\n"
"core.filemode=true\n"
"core.bare=false\n"
"core.logallrefupdates=true\n"
"remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*\n"
"remote.origin.url=https://github.com/quantcast/qfs.git\n"
"branch.master.remote=origin\n"
"branch.master.merge=refs/heads/master\n"
"git status:\n"
"?? krb5-1.13.2.tar.gz\n"
"?? krb5-1.13.2/\n"
"git branch:\n"
"* master 30ce7d55a2874badc9b82d73b539f705356495b5 Hadoop shim: allow to set effective user, group, and group membership with fs.qfs.euser, qfs.qfs.egroup, and fs.qfs.egroups configuration properties. Testing: ~/git/qfs/src/test-scripts/qfshadoop.sh fs -Dfs.qfs.euser=0 -Dfs.qfs.egroup=0 -touchz mytestfile ; ~/git/qfs/src/test-scripts/qfshadoop.sh fs -Dfs.qfs.euser=0 -Dfs.qfs.egroup=0 -ls mytestfile\n"
"git remote:\n"
"origin	https://github.com/quantcast/qfs.git (fetch)\n"
"origin	https://github.com/quantcast/qfs.git (push)\n"
"version:\n"
"https://github.com/quantcast/qfs.git/master@30ce7d55a2874badc9b82d73b539f705356495b5\n"
"KFS_BUILD_INFO_END\n"
;

static std::string MakeVersionHash()
{
    Hsieh_hash_fcn f;
    unsigned int h = (unsigned int)f(KFS_BUILD_INFO_STRING);
    std::string ret(2 * sizeof(h), '0');
    for (size_t i = ret.length() - 1; h != 0; i--) {
        ret[i] = "0123456789ABCDEF"[h & 0xF];
        h >>= 4;
    }
    return ret;
}

const std::string KFS_BUILD_VERSION_STRING(
    std::string("1.1.4-30ce7d55a2874badc9b82d73b539f705356495b5-RelWithDebInfo-") +
    MakeVersionHash()
);

const std::string KFS_SOURCE_REVISION_STRING(
    "1.1.4-https://github.com/quantcast/qfs.git/master@30ce7d55a2874badc9b82d73b539f705356495b5"
);

}

