# Copyright 2013 Jike Inc. All Rights Reserved.
# Author: Liqiang Guo(guoliqiang@jike.com)
# Date  : 2013-09-14 20:06:14


WORK_ROOT=../../../..
PROJ_NAME=util/unionfind_set/internal/unittest


all:
	$(WORK_ROOT)/develop/snake/snake.sh t=*
	if test $$? -ne 0; then exit 1; fi; \
  cp $(WORK_ROOT)/.snake/dbg/$(PROJ_NAME)/unionfind_set_unittest $(WORK_ROOT)/$(PROJ_NAME)/; \

opt:


clean:

